name: "Build & Deploy Site"
run-name: "Build & Deploy Site"
on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout site"
        uses: actions/checkout@v4
      - name: "install zola"
        run: |
          cd "$GITHUB_WORKSPACE"
          mkdir -p .bin
          curl -sSLo .bin/zola.tar.gz https://github.com/getzola/zola/releases/download/v0.21.0/zola-v0.21.0-x86_64-unknown-linux-musl.tar.gz
          tar -xzf .bin/zola.tar.gz -C .bin
          echo "$GITHUB_WORKSPACE/.bin" >> $GITHUB_PATH
      - name: "build site"
        run: "zola build"
      - name: "upload site"
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-upload
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: "deploy site"
        id: deployment
        uses: actions/deploy-pages@v4

